// Generated by CIRCT firtool-1.109.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module HandshakeSingleDelay(	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
  input         clock,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
                reset,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
  output        i0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:35:16
  input         i0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:35:16
  input  [31:0] i0_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:35:16
  input         o0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:36:16
  output        o0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:36:16
  output [31:0] o0_data	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:36:16
);

  reg         valid;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:37:24
  reg  [31:0] data;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:38:19
  wire        i0_ready_0 = ~valid | o0_ready;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:37:24, :39:{17,24}
  always @(posedge clock) begin	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
    automatic logic _GEN;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:21:15
    _GEN = i0_ready_0 & i0_valid;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:21:15, :39:24
    if (reset)	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
      valid <= 1'h0;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7, :37:24
    else	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
      valid <= _GEN | ~(o0_ready & valid) & valid;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:21:15, :37:24, :42:20, :43:15, :45:20, :46:15
    if (_GEN)	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:21:15
      data <= i0_data;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:38:19
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
    `ifdef FIRRTL_BEFORE_INITIAL	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
      `FIRRTL_BEFORE_INITIAL	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
      automatic logic [31:0] _RANDOM[0:1];	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
      `ifdef INIT_RANDOM_PROLOG_	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
        `INIT_RANDOM_PROLOG_	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
        end	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
        valid = _RANDOM[1'h0][0];	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7, :37:24
        data = {_RANDOM[1'h0][31:1], _RANDOM[1'h1][0]};	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7, :37:24, :38:19
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
      `FIRRTL_AFTER_INITIAL	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign i0_ready = i0_ready_0;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7, :39:24
  assign o0_valid = valid;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7, :37:24
  assign o0_data = data;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7, :38:19
endmodule

module vivado_fadd_blocking(	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:428:7
  input         aclk,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:430:18
                aclken,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:431:20
                aresetn,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:432:21
                s_axis_a_tvalid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:433:29
  output        s_axis_a_tready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:434:29
  input  [31:0] s_axis_a_tdata,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:435:28
  input         s_axis_b_tvalid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:436:29
  output        s_axis_b_tready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:437:29
  input  [31:0] s_axis_b_tdata,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:438:28
  output        m_axis_result_tvalid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:439:34
  input         m_axis_result_tready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:440:34
  output [31:0] m_axis_result_tdata	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:441:33
);

  wire [31:0] _add_out;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:444:25
  wire        _delay_i0_ready;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:443:27
  wire        delay_i0_valid = s_axis_a_tvalid & s_axis_b_tvalid;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:445:43
  wire        _s_axis_b_tready_T = _delay_i0_ready & delay_i0_valid;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:443:27, :445:43, :450:43
  HandshakeSingleDelay delay (	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:443:27
    .clock    (aclk),
    .reset    (~aresetn),	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:442:29
    .i0_ready (_delay_i0_ready),
    .i0_valid (delay_i0_valid),	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:445:43
    .i0_data  (_add_out),	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:444:25
    .o0_ready (m_axis_result_tready),
    .o0_valid (m_axis_result_tvalid),
    .o0_data  (m_axis_result_tdata)
  );	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:443:27
  float_add_dpi add (	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:444:25
    .a   (s_axis_a_tdata),
    .b   (s_axis_b_tdata),
    .out (_add_out)
  );	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:444:25
  assign s_axis_a_tready = _s_axis_b_tready_T;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:428:7, :450:43
  assign s_axis_b_tready = _s_axis_b_tready_T;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:428:7, :450:43
endmodule


