// Generated by CIRCT firtool-1.109.0
module op_FPOP_mul_I32W_I32W_O32W(	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:187:7
  output        i0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:188:16
  input         i0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:188:16
  input  [31:0] i0_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:188:16
  output        i1_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:189:16
  input         i1_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:189:16
  input  [31:0] i1_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:189:16
  input         o0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:190:16
  output        o0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:190:16
  output [31:0] o0_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:190:16
  input         clk,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:191:18
                reset	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:192:19
);

  vivado_fmul_blocking vivado_fmul_blocking (	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:194:21
    .s_axis_a_tvalid      (i0_valid),
    .s_axis_a_tready      (i0_ready),
    .s_axis_a_tdata       (i0_data),
    .s_axis_b_tvalid      (i1_valid),
    .s_axis_b_tready      (i1_ready),
    .s_axis_b_tdata       (i1_data),
    .m_axis_result_tvalid (o0_valid),
    .m_axis_result_tready (o0_ready),
    .m_axis_result_tdata  (o0_data)
  );	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:194:21
endmodule


