// Generated by CIRCT firtool-1.109.0
module op_FPOP_add_I32W_I32W_O32W(	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:158:7
  output        i0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:159:16
  input         i0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:159:16
  input  [31:0] i0_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:159:16
  output        i1_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:160:16
  input         i1_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:160:16
  input  [31:0] i1_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:160:16
  input         o0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:161:16
  output        o0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:161:16
  output [31:0] o0_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:161:16
  input         clk,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:162:18
                reset	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:163:19
);

  vivado_fadd_blocking vivado_fadd_blocking (	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:165:21
    .aclk                 (clk),
    .aclken               (1'h1),
    .aresetn              (~reset),	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:170:20
    .s_axis_a_tvalid      (i0_valid),
    .s_axis_a_tready      (i0_ready),
    .s_axis_a_tdata       (i0_data),
    .s_axis_b_tvalid      (i1_valid),
    .s_axis_b_tready      (i1_ready),
    .s_axis_b_tdata       (i1_data),
    .m_axis_result_tvalid (o0_valid),
    .m_axis_result_tready (o0_ready),
    .m_axis_result_tdata  (o0_data)
  );	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:165:21
endmodule


