// Generated by CIRCT firtool-1.109.0
module op_FP_1_0E_0__O32W(	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:220:7
  input         o0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:221:16
  output        o0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:221:16
  output [31:0] o0_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:221:16
  input         clk,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:222:18
                reset	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:223:19
);

  assign o0_valid = 1'h1;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:220:7
  assign o0_data = 32'h3F800000;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:220:7, :226:36
endmodule


