// Generated by CIRCT firtool-1.109.0
module op_SIToFP_I32W_O32W(	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:51:7
  output        i0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:52:16
  input         i0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:52:16
  input  [31:0] i0_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:52:16
  input         o0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:53:16
  output        o0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:53:16
  output [31:0] o0_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:53:16
  input         clk,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:54:18
                reset	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:55:19
);

  wire        _o0_data_res_shifts_T_22;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:34:35
  wire        _o0_data_res_shifts_T_21;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:34:35
  wire        _o0_data_res_shifts_T_20;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:34:35
  wire        _o0_data_res_shifts_T_19;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:34:35
  wire        _o0_data_res_shifts_T_18;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:34:35
  wire        _o0_data_res_shifts_T_17;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:34:35
  wire        _o0_data_res_shifts_T_16;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:34:35
  wire        _o0_data_res_shifts_T_15;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:34:35
  wire        _o0_data_res_shifts_T_14;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:34:35
  wire        _o0_data_res_shifts_T_13;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:34:35
  wire        _o0_data_res_shifts_T_12;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:34:35
  wire        _o0_data_res_shifts_T_11;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:34:35
  wire        _o0_data_res_shifts_T_10;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:34:35
  wire        _o0_data_res_shifts_T_9;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:34:35
  wire        _o0_data_res_shifts_T_8;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:34:35
  wire        _o0_data_res_shifts_T_7;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:34:35
  wire        _o0_data_res_shifts_T_6;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:34:35
  wire        _o0_data_res_shifts_T_5;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:34:35
  wire        _o0_data_res_shifts_T_4;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:34:35
  wire        _o0_data_res_shifts_T_3;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:34:35
  wire        _o0_data_res_shifts_T_2;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:34:35
  wire        o0_data_sign = $signed(i0_data) < 32'sh0;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:60:30, :61:57
  wire [31:0] o0_data_representation = o0_data_sign ? ~(i0_data - 32'h1) : i0_data;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:60:30, :61:{37,44,57}
  wire        _o0_data_res_T = o0_data_representation == 32'h0;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:44:23, :61:{37,57}
  wire [22:0] _o0_data_res_shifts_sequence_T = ~(o0_data_representation[22:0]);	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:27:33, :48:56, :61:37
  assign _o0_data_res_shifts_T_2 =
    _o0_data_res_shifts_T_3 & _o0_data_res_shifts_sequence_T[1];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:27:{33,41}, :34:35
  assign _o0_data_res_shifts_T_3 =
    _o0_data_res_shifts_T_4 & _o0_data_res_shifts_sequence_T[2];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:27:{33,41}, :34:35
  assign _o0_data_res_shifts_T_4 =
    _o0_data_res_shifts_T_5 & _o0_data_res_shifts_sequence_T[3];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:27:{33,41}, :34:35
  assign _o0_data_res_shifts_T_5 =
    _o0_data_res_shifts_T_6 & _o0_data_res_shifts_sequence_T[4];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:27:{33,41}, :34:35
  assign _o0_data_res_shifts_T_6 =
    _o0_data_res_shifts_T_7 & _o0_data_res_shifts_sequence_T[5];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:27:{33,41}, :34:35
  assign _o0_data_res_shifts_T_7 =
    _o0_data_res_shifts_T_8 & _o0_data_res_shifts_sequence_T[6];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:27:{33,41}, :34:35
  assign _o0_data_res_shifts_T_8 =
    _o0_data_res_shifts_T_9 & _o0_data_res_shifts_sequence_T[7];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:27:{33,41}, :34:35
  assign _o0_data_res_shifts_T_9 =
    _o0_data_res_shifts_T_10 & _o0_data_res_shifts_sequence_T[8];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:27:{33,41}, :34:35
  assign _o0_data_res_shifts_T_10 =
    _o0_data_res_shifts_T_11 & _o0_data_res_shifts_sequence_T[9];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:27:{33,41}, :34:35
  assign _o0_data_res_shifts_T_11 =
    _o0_data_res_shifts_T_12 & _o0_data_res_shifts_sequence_T[10];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:27:{33,41}, :34:35
  assign _o0_data_res_shifts_T_12 =
    _o0_data_res_shifts_T_13 & _o0_data_res_shifts_sequence_T[11];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:27:{33,41}, :34:35
  assign _o0_data_res_shifts_T_13 =
    _o0_data_res_shifts_T_14 & _o0_data_res_shifts_sequence_T[12];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:27:{33,41}, :34:35
  assign _o0_data_res_shifts_T_14 =
    _o0_data_res_shifts_T_15 & _o0_data_res_shifts_sequence_T[13];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:27:{33,41}, :34:35
  assign _o0_data_res_shifts_T_15 =
    _o0_data_res_shifts_T_16 & _o0_data_res_shifts_sequence_T[14];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:27:{33,41}, :34:35
  assign _o0_data_res_shifts_T_16 =
    _o0_data_res_shifts_T_17 & _o0_data_res_shifts_sequence_T[15];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:27:{33,41}, :34:35
  assign _o0_data_res_shifts_T_17 =
    _o0_data_res_shifts_T_18 & _o0_data_res_shifts_sequence_T[16];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:27:{33,41}, :34:35
  assign _o0_data_res_shifts_T_18 =
    _o0_data_res_shifts_T_19 & _o0_data_res_shifts_sequence_T[17];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:27:{33,41}, :34:35
  assign _o0_data_res_shifts_T_19 =
    _o0_data_res_shifts_T_20 & _o0_data_res_shifts_sequence_T[18];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:27:{33,41}, :34:35
  assign _o0_data_res_shifts_T_20 =
    _o0_data_res_shifts_T_21 & _o0_data_res_shifts_sequence_T[19];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:27:{33,41}, :34:35
  assign _o0_data_res_shifts_T_21 =
    _o0_data_res_shifts_T_22 & _o0_data_res_shifts_sequence_T[20];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:27:{33,41}, :34:35
  assign _o0_data_res_shifts_T_22 =
    _o0_data_res_shifts_sequence_T[22] & _o0_data_res_shifts_sequence_T[21];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:27:{33,41}, :34:35
  wire [4:0]  _o0_data_res_shifts_T_90 =
    {4'h0, _o0_data_res_shifts_sequence_T[22]} + {4'h0, _o0_data_res_shifts_T_22}
    + {4'h0, _o0_data_res_shifts_T_21} + {4'h0, _o0_data_res_shifts_T_20}
    + {4'h0, _o0_data_res_shifts_T_19} + {4'h0, _o0_data_res_shifts_T_18}
    + {4'h0, _o0_data_res_shifts_T_17} + {4'h0, _o0_data_res_shifts_T_16}
    + {4'h0, _o0_data_res_shifts_T_15} + {4'h0, _o0_data_res_shifts_T_14}
    + {4'h0, _o0_data_res_shifts_T_13} + {4'h0, _o0_data_res_shifts_T_12}
    + {4'h0, _o0_data_res_shifts_T_11} + {4'h0, _o0_data_res_shifts_T_10}
    + {4'h0, _o0_data_res_shifts_T_9} + {4'h0, _o0_data_res_shifts_T_8}
    + {4'h0, _o0_data_res_shifts_T_7} + {4'h0, _o0_data_res_shifts_T_6}
    + {4'h0, _o0_data_res_shifts_T_5} + {4'h0, _o0_data_res_shifts_T_4}
    + {4'h0, _o0_data_res_shifts_T_3} + {4'h0, _o0_data_res_shifts_T_2}
    + {4'h0, _o0_data_res_shifts_T_2 & _o0_data_res_shifts_sequence_T[0]} + 5'h1;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:21:57, :27:{33,41}, :34:35, :37:24
  wire [62:0] _o0_data_res_res_mantissa_T =
    {31'h0, o0_data_representation} << _o0_data_res_shifts_T_90;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:21:57, :37:24, :49:38, :61:37
  assign i0_ready = o0_ready;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:51:7
  assign o0_valid = i0_valid;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:51:7
  assign o0_data =
    {o0_data_sign,
     _o0_data_res_T ? 8'h0 : 8'h96 - {3'h0, _o0_data_res_shifts_T_90},
     _o0_data_res_T ? 23'h0 : _o0_data_res_res_mantissa_T[22:0]};	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:21:57, :37:24, :44:{23,32}, :45:21, :49:{30,38}, :50:{30,66}, :60:30, git/chisel-template/src/main/scala/hls_float/hls_float.scala:51:7, :59:40
endmodule


