// Generated by CIRCT firtool-1.109.0
module op_FpToSInt_I32W_O32W(	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:99:7
  output        i0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:100:16
  input         i0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:100:16
  input  [31:0] i0_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:100:16
  input         o0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:101:16
  output        o0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:101:16
  output [31:0] o0_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:101:16
  input         clk,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:102:18
                reset	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:103:19
);

  wire [23:0] _o0_data_res_T_3 = {1'h1, i0_data[22:0]} >> 8'h7F - i0_data[30:23] + 8'h17;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:243:58, :244:{44,64,79}, git/chisel-template/src/main/scala/hls_float/hls_float.scala:107:36
  assign i0_ready = o0_ready;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:99:7
  assign o0_valid = i0_valid;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:99:7
  assign o0_data =
    i0_data[31] ? {8'hFF, ~_o0_data_res_T_3} + 32'h1 : {8'h0, _o0_data_res_T_3};	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:244:{19,64}, :249:{19,32,37}, git/chisel-template/src/main/scala/hls_float/hls_float.scala:99:7, :107:36
endmodule


