// Generated by CIRCT firtool-1.109.0
module vivado_fmul_blocking(	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:397:7
  input         s_axis_a_tvalid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:399:29
  output        s_axis_a_tready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:400:29
  input  [31:0] s_axis_a_tdata,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:401:28
  input         s_axis_b_tvalid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:402:29
  output        s_axis_b_tready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:403:29
  input  [31:0] s_axis_b_tdata,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:404:28
  output        m_axis_result_tvalid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:405:34
  input         m_axis_result_tready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:406:34
  output [31:0] m_axis_result_tdata	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:407:33
);

  wire        _m_axis_result_tvalid_output = s_axis_a_tvalid & s_axis_b_tvalid;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:409:46
  wire        _s_axis_b_tready_T = m_axis_result_tready & _m_axis_result_tvalid_output;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:409:46, :410:45
  wire [2:0]  m_axis_result_tdata_Aidentity_res =
    (&(s_axis_a_tdata[30:23]))
      ? ((|(s_axis_a_tdata[22:0])) ? 3'h0 : {2'h1, ~(s_axis_a_tdata[31])})
      : s_axis_a_tdata[30:23] == 8'h0 & ~(|(s_axis_a_tdata[22:0])) ? 3'h4 : 3'h1;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:78:{25,48}, :79:{29,38}, :80:{29,38}, :81:25, :84:25, :88:21, :90:{31,39,53,61}, :91:17, :94:17, git/chisel-template/src/main/scala/hls_float/hls_float.scala:412:53
  wire [2:0]  m_axis_result_tdata_Bidentity_res =
    (&(s_axis_b_tdata[30:23]))
      ? ((|(s_axis_b_tdata[22:0])) ? 3'h0 : {2'h1, ~(s_axis_b_tdata[31])})
      : s_axis_b_tdata[30:23] == 8'h0 & ~(|(s_axis_b_tdata[22:0])) ? 3'h4 : 3'h1;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:78:{25,48}, :79:{29,38}, :80:{29,38}, :81:25, :84:25, :88:21, :90:{31,39,53,61}, :91:17, :94:17, git/chisel-template/src/main/scala/hls_float/hls_float.scala:412:92
  wire        _m_axis_result_tdata_T_14 =
    m_axis_result_tdata_Aidentity_res == 3'h3 | m_axis_result_tdata_Aidentity_res == 3'h2
    | m_axis_result_tdata_Bidentity_res == 3'h3
    | m_axis_result_tdata_Bidentity_res == 3'h2;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:78:48, :79:38, :90:61, :220:{24,51,63,91,103,130,142}
  wire        _m_axis_result_tdata_T_15 = m_axis_result_tdata_Aidentity_res == 3'h0;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:78:48, :79:38, :90:61, :223:29
  wire        _m_axis_result_tdata_T_16 = m_axis_result_tdata_Bidentity_res == 3'h0;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:78:48, :79:38, :90:61, :226:29
  wire        _m_axis_result_tdata_T_19 =
    m_axis_result_tdata_Aidentity_res == 3'h4 | m_axis_result_tdata_Bidentity_res == 3'h4;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:78:48, :79:38, :90:61, :229:{29,52,65}
  wire [47:0] _m_axis_result_tdata_mantissa_T_2 =
    {25'h1, s_axis_a_tdata[22:0]} * {25'h1, s_axis_b_tdata[22:0]};	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:234:57, git/chisel-template/src/main/scala/hls_float/hls_float.scala:412:{53,92}
  wire [23:0] _GEN = _m_axis_result_tdata_mantissa_T_2[46:23] + 24'h1;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:234:{57,88}, :235:66
  assign s_axis_a_tready = _s_axis_b_tready_T;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:397:7, :410:45
  assign s_axis_b_tready = _s_axis_b_tready_T;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:397:7, :410:45
  assign m_axis_result_tvalid = _m_axis_result_tvalid_output;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:397:7, :409:46
  assign m_axis_result_tdata =
    {_m_axis_result_tdata_T_14
       ? s_axis_a_tdata[31] ^ s_axis_b_tdata[31]
       : _m_axis_result_tdata_T_15
           ? s_axis_a_tdata[31]
           : _m_axis_result_tdata_T_16
               ? s_axis_b_tdata[31]
               : ~_m_axis_result_tdata_T_19 & (s_axis_a_tdata[31] ^ s_axis_b_tdata[31]),
     _m_axis_result_tdata_T_14 | _m_axis_result_tdata_T_15 | _m_axis_result_tdata_T_16
       ? 8'hFF
       : _m_axis_result_tdata_T_19
           ? 8'h0
           : s_axis_a_tdata[30:23] + s_axis_b_tdata[30:23]
             + {7'h0, _m_axis_result_tdata_mantissa_T_2[47]} - 8'h7F,
     _m_axis_result_tdata_T_14
       ? 23'h0
       : _m_axis_result_tdata_T_15 | _m_axis_result_tdata_T_16
           ? 23'h400000
           : _m_axis_result_tdata_T_19
               ? 23'h0
               : _m_axis_result_tdata_mantissa_T_2[47]
                   ? _GEN[23:1]
                   : _m_axis_result_tdata_mantissa_T_2[45:23]};	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:220:{51,91,130,171}, :221:{17,35}, :223:{29,52}, :224:17, :226:{29,52}, :227:17, :229:{52,89}, :230:17, :233:{22,35}, :234:{57,88}, :235:{26,32,41,66,71}, :236:41, :237:{26,37,65}, git/chisel-template/src/main/scala/hls_float/hls_float.scala:397:7, :412:{53,92,107}
endmodule


