// Generated by CIRCT firtool-1.109.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module HandshakeSingleDelay(	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
  input         clock,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
                reset,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
  output        i0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:35:16
  input         i0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:35:16
  input  [31:0] i0_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:35:16
  input         o0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:36:16
  output        o0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:36:16
  output [31:0] o0_data	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:36:16
);

  reg         valid;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:37:24
  reg  [31:0] data;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:38:19
  wire        i0_ready_0 = ~valid | o0_ready;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:37:24, :39:{17,24}
  always @(posedge clock) begin	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
    automatic logic _GEN;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:21:15
    _GEN = i0_ready_0 & i0_valid;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:21:15, :39:24
    if (reset)	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
      valid <= 1'h0;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7, :37:24
    else	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
      valid <= _GEN | ~(o0_ready & valid) & valid;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:21:15, :37:24, :42:20, :43:15, :45:20, :46:15
    if (_GEN)	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:21:15
      data <= i0_data;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:38:19
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
    `ifdef FIRRTL_BEFORE_INITIAL	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
      `FIRRTL_BEFORE_INITIAL	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
      automatic logic [31:0] _RANDOM[0:1];	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
      `ifdef INIT_RANDOM_PROLOG_	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
        `INIT_RANDOM_PROLOG_	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
        end	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
        valid = _RANDOM[1'h0][0];	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7, :37:24
        data = {_RANDOM[1'h0][31:1], _RANDOM[1'h1][0]};	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7, :37:24, :38:19
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
      `FIRRTL_AFTER_INITIAL	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign i0_ready = i0_ready_0;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7, :39:24
  assign o0_valid = valid;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7, :37:24
  assign o0_data = data;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:34:7, :38:19
endmodule

module vivado_fadd_blocking(	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:371:7
  input         aclk,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:373:18
                aclken,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:374:20
                aresetn,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:375:21
                s_axis_a_tvalid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:376:29
  output        s_axis_a_tready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:377:29
  input  [31:0] s_axis_a_tdata,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:378:28
  input         s_axis_b_tvalid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:379:29
  output        s_axis_b_tready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:380:29
  input  [31:0] s_axis_b_tdata,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:381:28
  output        m_axis_result_tvalid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:382:34
  input         m_axis_result_tready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:383:34
  output [31:0] m_axis_result_tdata	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:384:33
);

  wire        _delay_i0_ready;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:386:27
  wire [2:0]  delay_i0_data_Aidentity_res =
    (&(s_axis_a_tdata[30:23]))
      ? ((|(s_axis_a_tdata[22:0])) ? 3'h0 : {2'h1, ~(s_axis_a_tdata[31])})
      : s_axis_a_tdata[30:23] == 8'h0 & ~(|(s_axis_a_tdata[22:0])) ? 3'h4 : 3'h1;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:78:{25,48}, :79:{29,38}, :80:{29,38}, :81:25, :84:25, :88:21, :90:{31,39,53,61}, :91:17, :94:17, git/chisel-template/src/main/scala/hls_float/hls_float.scala:388:50
  wire [2:0]  delay_i0_data_Bidentity_res =
    (&(s_axis_b_tdata[30:23]))
      ? ((|(s_axis_b_tdata[22:0])) ? 3'h0 : {2'h1, ~(s_axis_b_tdata[31])})
      : s_axis_b_tdata[30:23] == 8'h0 & ~(|(s_axis_b_tdata[22:0])) ? 3'h4 : 3'h1;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:78:{25,48}, :79:{29,38}, :80:{29,38}, :81:25, :84:25, :88:21, :90:{31,39,53,61}, :91:17, :94:17, git/chisel-template/src/main/scala/hls_float/hls_float.scala:388:89
  wire        _delay_i0_data_T_15 = delay_i0_data_Aidentity_res == 3'h3;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:78:48, :79:38, :90:61, :130:25
  wire        _delay_i0_data_T_19 = delay_i0_data_Bidentity_res == 3'h2;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:78:48, :79:38, :90:61, :130:64
  wire        _delay_i0_data_T_18 = delay_i0_data_Bidentity_res == 3'h3;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:78:48, :79:38, :90:61, :130:104
  wire        _delay_i0_data_T_16 = delay_i0_data_Aidentity_res == 3'h2;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:78:48, :79:38, :90:61, :130:143
  wire        _delay_i0_data_T_14 =
    _delay_i0_data_T_15 & _delay_i0_data_T_19 | _delay_i0_data_T_18 & _delay_i0_data_T_16;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:130:{25,52,64,92,104,131,143}
  wire        _delay_i0_data_T_17 = _delay_i0_data_T_15 | _delay_i0_data_T_16;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:130:{25,143}, :133:56
  wire        _delay_i0_data_T_22 = delay_i0_data_Bidentity_res == 3'h4;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:78:48, :79:38, :90:61, :142:29
  wire [7:0]  _delay_i0_data_difference_T_2 =
    s_axis_a_tdata[30:23] - s_axis_b_tdata[30:23];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:154:63, git/chisel-template/src/main/scala/hls_float/hls_float.scala:388:{50,89}
  wire        _delay_i0_data_T_23 = s_axis_a_tdata[30:23] > s_axis_b_tdata[30:23];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:156:32, git/chisel-template/src/main/scala/hls_float/hls_float.scala:388:{50,89}
  wire [23:0] _GEN =
    {16'h0,
     $signed(_delay_i0_data_difference_T_2) < 8'sh0
       ? 8'h0 - _delay_i0_data_difference_T_2
       : _delay_i0_data_difference_T_2};	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:101:{16,23}, :102:{17,21}, :105:17, :154:63, :159:60
  wire [7:0]  delay_i0_data_exponent =
    _delay_i0_data_T_23 ? s_axis_a_tdata[30:23] : s_axis_b_tdata[30:23];	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:156:{32,49}, :157:26, :162:26, git/chisel-template/src/main/scala/hls_float/hls_float.scala:388:{50,89}
  wire [25:0] delay_i0_data_a_mantissa =
    _delay_i0_data_T_23
      ? {3'h1, s_axis_a_tdata[22:0]}
      : {2'h0, {1'h1, s_axis_a_tdata[22:0]} >> _GEN};	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:149:34, :156:{32,49}, :158:28, :159:60, :163:{28,34,60}, git/chisel-template/src/main/scala/hls_float/hls_float.scala:388:50
  wire [25:0] delay_i0_data_b_mantissa =
    _delay_i0_data_T_23
      ? {2'h0, {1'h1, s_axis_b_tdata[22:0]} >> _GEN}
      : {3'h1, s_axis_b_tdata[22:0]};	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:150:34, :156:{32,49}, :159:{28,34,60}, :164:28, git/chisel-template/src/main/scala/hls_float/hls_float.scala:388:89
  wire [25:0] delay_i0_data_a_mantissa_signed =
    s_axis_a_tdata[31] ? 26'h0 - delay_i0_data_a_mantissa : delay_i0_data_a_mantissa;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:112:27, :113:{17,20}, :116:17, :149:34, :168:45, git/chisel-template/src/main/scala/hls_float/hls_float.scala:388:50
  wire [25:0] delay_i0_data_b_mantissa_signed =
    s_axis_b_tdata[31] ? 26'h0 - delay_i0_data_b_mantissa : delay_i0_data_b_mantissa;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:112:27, :113:{17,20}, :116:17, :150:34, :169:45, git/chisel-template/src/main/scala/hls_float/hls_float.scala:388:89
  wire [25:0] delay_i0_data_sum =
    delay_i0_data_a_mantissa_signed + delay_i0_data_b_mantissa_signed;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:152:34, :168:45, :169:45, :173:37
  wire        _delay_i0_data_res_sign_T = $signed(delay_i0_data_sum) < 26'sh0;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:101:16, :152:34
  wire [25:0] delay_i0_data_mantissa_res =
    _delay_i0_data_res_sign_T ? 26'h0 - delay_i0_data_sum : delay_i0_data_sum;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:101:{16,23}, :102:{17,21}, :105:17, :152:34
  wire [15:0] _delay_i0_data_rev_man_T_9 =
    {8'h0, delay_i0_data_mantissa_res[15:8]} | {delay_i0_data_mantissa_res[7:0], 8'h0};	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:101:23, :102:17, :105:17, :175:32
  wire [15:0] _delay_i0_data_rev_man_T_19 =
    {4'h0, _delay_i0_data_rev_man_T_9[15:4] & 12'hF0F}
    | {_delay_i0_data_rev_man_T_9[11:0] & 12'hF0F, 4'h0};	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:175:32
  wire [15:0] _delay_i0_data_rev_man_T_29 =
    {2'h0, _delay_i0_data_rev_man_T_19[15:2] & 14'h3333}
    | {_delay_i0_data_rev_man_T_19[13:0] & 14'h3333, 2'h0};	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:175:32
  wire [14:0] _delay_i0_data_rev_man_T_39 =
    _delay_i0_data_rev_man_T_29[15:1] & 15'h5555
    | {1'h0, _delay_i0_data_rev_man_T_29[12:0] & 13'h1555, 1'h0};	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:175:32
  wire [7:0]  _delay_i0_data_rev_man_T_50 =
    {4'h0, delay_i0_data_mantissa_res[23:20]} | {delay_i0_data_mantissa_res[19:16], 4'h0};	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:101:23, :102:17, :105:17, :175:32
  wire [7:0]  _delay_i0_data_rev_man_T_60 =
    {2'h0, _delay_i0_data_rev_man_T_50[7:2] & 6'h33}
    | {_delay_i0_data_rev_man_T_50[5:0] & 6'h33, 2'h0};	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:175:32
  wire [7:0]  _delay_i0_data_rev_man_T_70 =
    {1'h0, _delay_i0_data_rev_man_T_60[7:1] & 7'h55}
    | {_delay_i0_data_rev_man_T_60[6:0] & 7'h55, 1'h0};	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:175:32
  wire [23:0] _delay_i0_data_res_mantissa_T = delay_i0_data_mantissa_res[23:0] + 24'h1;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:101:23, :102:17, :105:17, :178:44
  wire        _GEN_0 =
    _delay_i0_data_T_18 | _delay_i0_data_T_19 | delay_i0_data_Aidentity_res == 3'h4;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:78:48, :79:38, :90:61, :130:{64,104}, :136:{56,97}, :137:17, :139:{29,53}, :140:17, :142:53
  wire [56:0] _delay_i0_data_res_mantissa_T_57 =
    {31'h0, delay_i0_data_mantissa_res}
    << (delay_i0_data_mantissa_res[25]
          ? 5'h0
          : delay_i0_data_mantissa_res[24]
              ? 5'h1
              : _delay_i0_data_rev_man_T_70[0]
                  ? 5'h2
                  : _delay_i0_data_rev_man_T_70[1]
                      ? 5'h3
                      : _delay_i0_data_rev_man_T_70[2]
                          ? 5'h4
                          : _delay_i0_data_rev_man_T_70[3]
                              ? 5'h5
                              : _delay_i0_data_rev_man_T_70[4]
                                  ? 5'h6
                                  : _delay_i0_data_rev_man_T_70[5]
                                      ? 5'h7
                                      : _delay_i0_data_rev_man_T_70[6]
                                          ? 5'h8
                                          : _delay_i0_data_rev_man_T_70[7]
                                              ? 5'h9
                                              : _delay_i0_data_rev_man_T_39[0]
                                                  ? 5'hA
                                                  : _delay_i0_data_rev_man_T_39[1]
                                                      ? 5'hB
                                                      : _delay_i0_data_rev_man_T_39[2]
                                                          ? 5'hC
                                                          : _delay_i0_data_rev_man_T_39[3]
                                                              ? 5'hD
                                                              : _delay_i0_data_rev_man_T_39[4]
                                                                  ? 5'hE
                                                                  : _delay_i0_data_rev_man_T_39[5]
                                                                      ? 5'hF
                                                                      : _delay_i0_data_rev_man_T_39[6]
                                                                          ? 5'h10
                                                                          : _delay_i0_data_rev_man_T_39[7]
                                                                              ? 5'h11
                                                                              : _delay_i0_data_rev_man_T_39[8]
                                                                                  ? 5'h12
                                                                                  : _delay_i0_data_rev_man_T_39[9]
                                                                                      ? 5'h13
                                                                                      : _delay_i0_data_rev_man_T_39[10]
                                                                                          ? 5'h14
                                                                                          : _delay_i0_data_rev_man_T_39[11]
                                                                                              ? 5'h15
                                                                                              : _delay_i0_data_rev_man_T_39[12]
                                                                                                  ? 5'h16
                                                                                                  : _delay_i0_data_rev_man_T_39[13]
                                                                                                      ? 5'h17
                                                                                                      : {4'hC,
                                                                                                         ~(_delay_i0_data_rev_man_T_39[14])})
    - 5'h2;	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:101:23, :102:17, :105:17, :175:32, :188:{47,75}, src/main/scala/chisel3/util/MuxImpl.scala:31:84, src/main/scala/chisel3/util/OneHot.scala:48:45
  HandshakeSingleDelay delay (	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:386:27
    .clock    (aclk),
    .reset    (~aresetn),	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:385:29
    .i0_ready (_delay_i0_ready),
    .i0_valid (s_axis_a_tvalid & s_axis_b_tvalid),	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:387:43
    .i0_data
      ({_delay_i0_data_T_14
          | (_delay_i0_data_T_17
               ? s_axis_a_tdata[31]
               : _GEN_0
                   ? s_axis_b_tdata[31]
                   : _delay_i0_data_T_22
                       ? s_axis_a_tdata[31]
                       : _delay_i0_data_res_sign_T),
        _delay_i0_data_T_14
          ? 8'hFF
          : _delay_i0_data_T_17
              ? s_axis_a_tdata[30:23]
              : _GEN_0
                  ? s_axis_b_tdata[30:23]
                  : _delay_i0_data_T_22
                      ? s_axis_a_tdata[30:23]
                      : delay_i0_data_mantissa_res[24]
                          ? ((|delay_i0_data_sum) ? delay_i0_data_exponent : 8'h0) + 8'h1
                          : delay_i0_data_mantissa_res[23]
                              ? ((|delay_i0_data_sum) ? delay_i0_data_exponent : 8'h0)
                              : ((|delay_i0_data_sum) ? delay_i0_data_exponent : 8'h0)
                                - {3'h0,
                                   delay_i0_data_mantissa_res[25]
                                     ? 5'h0
                                     : delay_i0_data_mantissa_res[24]
                                         ? 5'h1
                                         : _delay_i0_data_rev_man_T_70[0]
                                             ? 5'h2
                                             : _delay_i0_data_rev_man_T_70[1]
                                                 ? 5'h3
                                                 : _delay_i0_data_rev_man_T_70[2]
                                                     ? 5'h4
                                                     : _delay_i0_data_rev_man_T_70[3]
                                                         ? 5'h5
                                                         : _delay_i0_data_rev_man_T_70[4]
                                                             ? 5'h6
                                                             : _delay_i0_data_rev_man_T_70[5]
                                                                 ? 5'h7
                                                                 : _delay_i0_data_rev_man_T_70[6]
                                                                     ? 5'h8
                                                                     : _delay_i0_data_rev_man_T_70[7]
                                                                         ? 5'h9
                                                                         : _delay_i0_data_rev_man_T_39[0]
                                                                             ? 5'hA
                                                                             : _delay_i0_data_rev_man_T_39[1]
                                                                                 ? 5'hB
                                                                                 : _delay_i0_data_rev_man_T_39[2]
                                                                                     ? 5'hC
                                                                                     : _delay_i0_data_rev_man_T_39[3]
                                                                                         ? 5'hD
                                                                                         : _delay_i0_data_rev_man_T_39[4]
                                                                                             ? 5'hE
                                                                                             : _delay_i0_data_rev_man_T_39[5]
                                                                                                 ? 5'hF
                                                                                                 : _delay_i0_data_rev_man_T_39[6]
                                                                                                     ? 5'h10
                                                                                                     : _delay_i0_data_rev_man_T_39[7]
                                                                                                         ? 5'h11
                                                                                                         : _delay_i0_data_rev_man_T_39[8]
                                                                                                             ? 5'h12
                                                                                                             : _delay_i0_data_rev_man_T_39[9]
                                                                                                                 ? 5'h13
                                                                                                                 : _delay_i0_data_rev_man_T_39[10]
                                                                                                                     ? 5'h14
                                                                                                                     : _delay_i0_data_rev_man_T_39[11]
                                                                                                                         ? 5'h15
                                                                                                                         : _delay_i0_data_rev_man_T_39[12]
                                                                                                                             ? 5'h16
                                                                                                                             : _delay_i0_data_rev_man_T_39[13]
                                                                                                                                 ? 5'h17
                                                                                                                                 : {4'hC,
                                                                                                                                    ~(_delay_i0_data_rev_man_T_39[14])}}
                                + 8'h2,
        _delay_i0_data_T_14
          ? 23'h400000
          : _delay_i0_data_T_17
              ? s_axis_a_tdata[22:0]
              : _GEN_0
                  ? s_axis_b_tdata[22:0]
                  : _delay_i0_data_T_22
                      ? s_axis_a_tdata[22:0]
                      : delay_i0_data_mantissa_res[24]
                          ? _delay_i0_data_res_mantissa_T[23:1]
                          : delay_i0_data_mantissa_res[23]
                              ? delay_i0_data_mantissa_res[22:0]
                              : _delay_i0_data_res_mantissa_T_57[22:0]}),	// git/chisel-template/src/main/scala/floatingpoint/FloatingPoint.scala:101:{16,23}, :102:17, :105:17, :130:{92,173}, :131:17, :133:{56,97}, :134:17, :136:{56,97}, :137:17, :139:53, :140:17, :142:{29,53}, :143:17, :152:34, :156:49, :157:26, :162:26, :175:32, :176:{26,35}, :177:{30,36,41,64}, :178:{30,44}, :180:28, :181:15, :182:{32,38,43}, :183:{32,43}, :187:{34,40,45,69,95}, :188:{34,47,81}, :192:22, git/chisel-template/src/main/scala/hls_float/hls_float.scala:388:{50,89,104}, src/main/scala/chisel3/util/MuxImpl.scala:31:84, src/main/scala/chisel3/util/OneHot.scala:48:45
    .o0_ready (m_axis_result_tready),
    .o0_valid (m_axis_result_tvalid),
    .o0_data  (m_axis_result_tdata)
  );	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:386:27
  assign s_axis_a_tready = _delay_i0_ready;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:371:7, :386:27
  assign s_axis_b_tready = _delay_i0_ready;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:371:7, :386:27
endmodule


