// Generated by CIRCT firtool-1.109.0
module op_HLS_BUF_P_0_I16W_O16W(	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:521:7
  output        i0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:524:14
  input         i0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:524:14
  input  [15:0] i0_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:524:14
  input         o0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:525:14
  output        o0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:525:14
  output [15:0] o0_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:525:14
  input         clk,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:526:15
                reset	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:527:17
);

  assign i0_ready = o0_ready;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:521:7
  assign o0_valid = i0_valid;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:521:7
  assign o0_data = i0_data;	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:521:7
endmodule


