// Generated by CIRCT firtool-1.109.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module op_HLS_BUF_P_1_I8W_O8W_Queue1_UInt8(	// src/main/scala/chisel3/util/Queue.scala:60:7
  input        clock,	// src/main/scala/chisel3/util/Queue.scala:60:7
               reset,	// src/main/scala/chisel3/util/Queue.scala:60:7
  output       io_enq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input        io_enq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [7:0] io_enq_bits,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input        io_deq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output       io_deq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [7:0] io_deq_bits,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output       io_count	// src/main/scala/chisel3/util/Queue.scala:72:14
);

  reg  [7:0] ram;	// src/main/scala/chisel3/util/Queue.scala:73:44
  reg        full;	// src/main/scala/chisel3/util/Queue.scala:76:27
  wire       io_deq_valid_0 = io_enq_valid | full;	// src/main/scala/chisel3/util/Queue.scala:76:27, :102:16, :114:{24,39}
  wire       do_enq = ~(~full & io_deq_ready) & ~full & io_enq_valid;	// src/main/scala/chisel3/util/Queue.scala:76:27, :78:28, :80:27, :103:19, :115:17, :118:{26,35}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Queue.scala:60:7
    if (reset)	// src/main/scala/chisel3/util/Queue.scala:60:7
      full <= 1'h0;	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
    else if (~(do_enq == (full & io_deq_ready & io_deq_valid_0)))	// src/main/scala/chisel3/util/Queue.scala:76:27, :80:27, :81:27, :93:{15,27}, :94:16, :102:16, :114:{24,39}, :115:17, :117:14, :118:{26,35}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      full <= do_enq;	// src/main/scala/chisel3/util/Queue.scala:76:27, :80:27, :115:17, :118:{26,35}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    if (do_enq)	// src/main/scala/chisel3/util/Queue.scala:80:27, :115:17, :118:{26,35}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      ram <= io_enq_bits;	// src/main/scala/chisel3/util/Queue.scala:73:44
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/chisel3/util/Queue.scala:60:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/chisel3/util/Queue.scala:60:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/chisel3/util/Queue.scala:60:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/chisel3/util/Queue.scala:60:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/chisel3/util/Queue.scala:60:7
        full = _RANDOM[/*Zero width*/ 1'b0][0];	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
        ram = _RANDOM[/*Zero width*/ 1'b0][8:1];	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:44, :76:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/chisel3/util/Queue.scala:60:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_enq_ready = ~full;	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27, :103:19
  assign io_deq_valid = io_deq_valid_0;	// src/main/scala/chisel3/util/Queue.scala:60:7, :102:16, :114:{24,39}
  assign io_deq_bits = full ? ram : io_enq_bits;	// src/main/scala/chisel3/util/Queue.scala:60:7, :73:44, :76:27, :108:17, :115:17, :116:19
  assign io_count = full;	// src/main/scala/chisel3/util/Queue.scala:60:7, :76:27
endmodule

module op_HLS_BUF_P_1_I8W_O8W(	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:521:7
  output       i0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:524:14
  input        i0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:524:14
  input  [7:0] i0_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:524:14
  input        o0_ready,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:525:14
  output       o0_valid,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:525:14
  output [7:0] o0_data,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:525:14
  input        clk,	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:526:15
               reset	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:527:17
);

  op_HLS_BUF_P_1_I8W_O8W_Queue1_UInt8 queue (	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:531:27
    .clock        (clk),
    .reset        (reset),
    .io_enq_ready (i0_ready),
    .io_enq_valid (~reset & i0_valid),	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:532:22, :533:21, :534:30
    .io_enq_bits  (i0_data),
    .io_deq_ready (o0_ready),
    .io_deq_valid (o0_valid),
    .io_deq_bits  (o0_data),
    .io_count     (/* unused */)
  );	// git/chisel-template/src/main/scala/hls_float/hls_float.scala:531:27
endmodule


